### PR TITLE
Fix WiX warnings

### PR DESCRIPTION
**Pull request by bryanwweber**
@speth I made some changes to the way the registry keys are created and deleted in the wxsgen.py file, because WiX was complaining about the @Action key being deprecated: http://wixtoolset.org/documentation/manual/v3/xsd/wix/registrykey.html Please let me know if these changes break anything, or if there's a different way you'd prefer to handle the options (for instance, combining the dictionary creation into reg_options, so that only that is passed into addRegistryKey)!

Thanks!
Bryan

### CODE REVIEW

**Comment by speth** [comment]
Actually, the documentation you linked to seems to imply that the installer will automatically create and remove the key as needed, since there are no sub-keys. If that is in fact correct, the simpler solution is to just drop the Action.

**Comment by bryanwweber** [comment]
I wasn't sure what they meant by that. I guess they mean if Cantera (as opposed to the installer) created registry keys, then you'd have to include that action? In any case, I'll check what the various options do tomorrow.

Thanks!
Bryan

**Comment by bryanwweber** [comment]
So, although it isn't listed in the docs, removing `ForceCreateOnInstall` and `ForceDeleteOnUninstall` generates the error

```
error CNDL0037 : The RegistryKey/@Id attribute can only be specified with one 
of the following attributes: ForceCreateOnInstall or ForceDeleteOnUninstall present 
with value 'yes'.
```

I don't know which it would be better to keep, since it seems like neither should be necessary according to the docs. Perhaps best to keep both then?

**Comment by speth** [comment]
Maybe the implication is that it would create and remove the `RegistryKey` automatically if we just created the `RegistryValue` directly. But I'm fine with the simpler fix that you suggested, with both flags set to "yes".

**Pull request closed without merging**
