### PR TITLE
Implement elemental mass fraction, mixutre fraction

### PR DESCRIPTION
**Pull request by thomasfiala**
Hi,

I wrote a procedure to compute elemental mass fractions of Phase objects.
This could be used to compute the mixture fraction in counterflow diffusion flames.

### CODE REVIEW

**Comment by speth** [comment]
I think this is an interesting feature. I'd probably also add the analogous functions for elemental mole fraction. I'm not sure whether or not the array version of the function, `getElementalMassFractions(doublereal* const emf)` is particularly useful.

**Comment by thomasfiala** [comment]
I removed `getElementalMassFractions` which I just added to match other functions present. You're right, it probably is of little use.

I also added a function `elementalMoleFraction`. I find the name a bit confusing, though. What I'm actually calculating is the number of atoms of a certain element divided by the total number of atoms present. However, this name is probably better than everything else.
Could you also please have a look over the implementation of the elementalMoleFunction? I did not find a formula for it in literature, so I had to come up with one myself.

**Comment by speth** [comment]
I think your implementation of `elementalMoleFraction` is correct. I don't know a better name for it, but the quantity is certainly useful to know in some situations.

I made some modifications, mostly to the docs to get the Sphinx and Doxygen docs working correctly, in this branch: https://github.com/Cantera/cantera/commits/elementalmassfraction

One minor question I still have is over the terminology `Z_m(m)` where the first `m` stands for "mass" (I think) and the second is the element index, even though subscript `m` in the formula means element index. Is this notation used elsewhere, or is it possible to avoid it? Cantera usually uses `k` for species indices and `m` for element indices, but it might be better in this case to use something else for clarity.

**Comment by thomasfiala** [comment]
Thanks a lot for the simplifications and the documentation improvements!
I originally termed the elemental mass fraction `Z_m` to distinguish it from the elemental mole fraction and the mixture fraction, which are all often named `Z`. What do you think about `Z_mass` and `Z_mole` instead of `Z_m` and `Z_n`, and leaving the mixture fraction `Z`?
Each book I looked at appears to have a separate terming for the elemental mass fraction and the mixture fraction. None of them are practical for Cantera (e.g. many use a lower case `z` for the mixture fraction, which would lead to confusion with the axial coordinate in Cantera.). So I guess you'll have to decide on an intuitive and consistent formulation ourselves.

**Comment by speth** [comment]
Commited to SVN trunk as [r3385](https://code.google.com/p/cantera/source/detail?r=3385) and [r3386](https://code.google.com/p/cantera/source/detail?r=3386). Thanks for submitting these additions.

**Pull request closed without merging**
